version: 1

context:
  small:
    include:
      - ARCHITECTURE.md
      - SNAPSHOT.md
      - README.md
      - pyproject.toml
      - package.json
      - frontend/package.json
      - contracts/**
  large:
    roots: [backend, app, src, frontend]
    exclude_dirs:
      - .git
      - .venv
      - venv
      - node_modules
      - dist
      - build
      - .next
      - __pycache__
      - __pypackages__
      - .pytest_cache
      - .mypy_cache
      - .ruff_cache
    exclude_globs: ["**/*.min.js", "**/*.map"]
    max_files: 220
    max_kb_each: 64

evidence:
  commands:
    - git status --porcelain=v1 || true
    - git diff || true
    - python --version || true
    - node --version || true
    - npm --version || true

dlp:
  enable: true
  block_on_detect: true
  mask: true
  allowlist_files:
    - ".env.example"
    - "frontend/.env.example"

guard:
  forbid_full_rewrite: true
  allow_full_rewrite_globs:
    - "core/aiguard.py"
    - ".github/workflows/oceansguard.yml"


checks:
  commands:
    # =========================
    # Backend (Python)
    # =========================
    - >
      python -c "import os,sys,subprocess;
      targets=[d for d in ('backend','app','src') if os.path.isdir(d)];
      sys.exit(subprocess.call([sys.executable,'-m','compileall',*targets]) if targets else 0)"

    - >
      python -c "import os,sys,subprocess,importlib.util;
      targets=[d for d in ('backend','app','src') if os.path.isdir(d)];
      has=importlib.util.find_spec('ruff') is not None;
      sys.exit(subprocess.call([sys.executable,'-m','ruff','check',*targets]) if (has and targets) else 0)"

    - >
      python -c "import os,sys,subprocess,importlib.util;
      targets=[d for d in ('backend','app','src') if os.path.isdir(d)];
      has=importlib.util.find_spec('mypy') is not None;
      sys.exit(subprocess.call([sys.executable,'-m','mypy',*targets]) if (has and targets) else 0)"

    - >
      python -c "import os,sys,subprocess,importlib.util;
      has=importlib.util.find_spec('pytest') is not None;
      has_tests=any(os.path.isdir(p) for p in ('tests','backend/tests','app/tests','src/tests'));
      sys.exit(subprocess.call([sys.executable,'-m','pytest','-q']) if (has and has_tests) else 0)"

    # =========================
    # Frontend (React)
    # =========================
    - >
      python -c "import os,sys,subprocess;
      d='frontend';
      sys.exit(0 if not os.path.isdir(d) else (subprocess.call('npm ci --silent', cwd=d, shell=True) if os.path.exists(os.path.join(d,'package-lock.json')) else subprocess.call('npm install --silent', cwd=d, shell=True)))"

    - >
      python -c "import os,sys,subprocess;
      d='frontend';
      sys.exit(0 if not os.path.isdir(d) else subprocess.call('npm run build --silent', cwd=d, shell=True))"

output:
  pack: ai_context_pack.md
  audit: CHANGELOG_AI.md
  testlog: ai_test_last.log
  report_json: ai_check_report.json
