# core/aiguard.py
from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from datetime import datetime


def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def die(msg: str) -> None:
    raise SystemExit(f"[OceansGuard] {msg}")


def copy_if_missing(src: Path, dst: Path) -> None:
    if dst.exists():
        print(f"[skip] exists: {dst}")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)
    print(f"[create] {dst}")


def write_if_missing(dst: Path, content: str) -> None:
    if dst.exists():
        print(f"[skip] exists: {dst}")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content, encoding="utf-8")
    print(f"[create] {dst}")


def cmd_init(repo: Path) -> None:
    """
    init は「コピー専用」。
    - templates/.aiguard.yml を .aiguard.yml にコピー（上書きしない）
    - ARCHITECTURE.md / SNAPSHOT.md を無ければ作成
    - contracts/ を無ければ作成
    """
    here = Path(__file__).resolve()
    guard_root = here.parent.parent  # OceansGuard/
    templates = guard_root / "templates"

    tpl_aiguard = templates / ".aiguard.yml"
    if not tpl_aiguard.exists():
        die("templates/.aiguard.yml not found")

    # 1) .aiguard.yml
    copy_if_missing(tpl_aiguard, repo / ".aiguard.yml")

    # 2) ARCHITECTURE.md / SNAPSHOT.md
    write_if_missing(
        repo / "ARCHITECTURE.md",
        "# ARCHITECTURE\n\n"
        "- レイヤ構成\n"
        "- 依存方向\n"
        "- 外部I/O（API/DB）\n\n"
        f"_generated by OceansGuard init @ {now_iso()}_\n",
    )
    write_if_missing(
        repo / "SNAPSHOT.md",
        "# SNAPSHOT\n\n"
        "- 現在の仕様\n"
        "- 既知の制約\n"
        "- 触ってはいけない領域\n\n"
        f"_generated by OceansGuard init @ {now_iso()}_\n",
    )

    # 3) contracts/
    contracts = repo / "contracts"
    if not contracts.exists():
        contracts.mkdir(parents=True, exist_ok=True)
        (contracts / "README.md").write_text(
            "# Contracts\n\n"
            "このディレクトリには、守るべき契約を置きます。\n\n"
            "- OpenAPI（FastAPI の openapi.yaml）\n"
            "- DB schema snapshot\n"
            "- UI DTO / 型\n\n",
            encoding="utf-8",
        )
        print(f"[create] {contracts}/README.md")
    else:
        print(f"[skip] exists: {contracts}/")

    print("[OK] init completed")


def main() -> None:
    ap = argparse.ArgumentParser(prog="aiguard")
    ap.add_argument("command", choices=["init", "pack", "check", "run"])
    ap.add_argument("--repo", default=".")
    ap.add_argument("--task", default="")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()

    if args.command == "init":
        cmd_init(repo)
        return

    # pack / check / run は既存実装を使用
    die("This build only finalizes init. Use previous implementation for pack/check/run.")


if __name__ == "__main__":
    main()
